---
- name: Generate Device Configuration
  connection: local
  hosts: device_roles_access,device_roles_distribution 
  gather_facts: False

  roles:
    - role: generate_config
      tags: generate_config 
